### ISSUE TITLE
Minor Conflict with autodie

### ISSUE THREAD

**Issue by iwelch** [Perl-Email-Project/Email-Send#5]
```
#!/usr/bin/perl -w
use strict;
use warnings FATAL => qw{ uninitialized };
use autodie;
use Email::Send;

```

leads to

```

perl test.pl                                                                                     |use vars qw[$VERSION];
Subroutine main::send redefined at /opt/local/lib/perl5/site_perl/5.22/Email/Send.pm line 273.   |$VERSION   = '2.201';
Prototype mismatch: sub main::send (*$$;$) vs none at /opt/local/lib/perl5/site_perl/5.22/Email/\|
Send.pm line 273.                                                                                |use Email::Simple 1.92;


```
I am still using Send instead of Sender, because the whole shebang fails compiling on OSX (probably on Moo).

**Comment by genio** [comment]
@iwelch Sorry it has taken me so long to notice this.  It seems I failed to do the very first thing I should have done, _watch_ this repository.  Oops.

You are using Perl 5.22, so you should have no problems using Email::Sender.  I'd like to resolve that problem first, if possible.  People really should be using that instead.

Second, It seems you're putting the wrong Perl path in the shebang line.  ```#!/usr/bin/env perl``` is more likely what you want.

However, a work-around to your particular error case can be done via:

```perl
#!/usr/bin/env perl
# are you sure you want the -w switch? That can introduce issues.
use strict;
use warnings FATAL => qw{ uninitialized };
use autodie;
no autodie 'send';  # this works around the issue you're describing
use Email::Send;
```

If I've misinterpreted anything, please let me know.

-- Chase

**Comment by genio** [comment]
The other option, which I should have mentioned first, is to tell Email::Send not to export anything.  This way, the ```send``` function is never put in the ```main``` namespace. 

```perl
#!/usr/bin/env perl
use strict;
use warnings FATAL => qw{ uninitialized };
use autodie;
use Email::Send ();
```

**Comment by iwelch** [comment]
hi chase---it is not Email::Sender's fault, but the cpan install on my
system fails on some of its prerequisites.  my OSX is current, and
developer tools are installed.  I am enclosing a log file in case it is of
interest.  (I do not need this to be fixed!)  maybe it helps.  regards, /iaw


----
Ivo Welch (ivo.welch@gmail.com)
http://www.ivo-welch.info/
J. Fred Weston Professor of Finance
Anderson School at UCLA, C519
Free Finance Textbook, http://book.ivo-welch.info/
Editor, Critical Finance Review, http://www.critical-finance-review.org/

**Comment by genio** [comment]
@iwelch  I'm going to close out this issue (assuming the work-arounds provided have helped you out).  If you'd like to discuss how to fix up your Perl installation, IRC is a much easier means of doing so and everyone there would be happy to help:

https://chat.mibbit.com/?channel=%23perl&server=irc.perl.org
